spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/loyalty?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.mariadb.jdbc.Driver
    database: MYSQL
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.auto: validate
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.integration.envers.enabled: false