spring:
  ldap:
    base: dc=dbs,dc=com
    attribute: uid
    role: Maker
    embedded:
      base-dn: dc=dbs,dc=com
      ldif: classpath:schema.ldif
      port: 8389
      credential:
        username: uid=admin
        password: password