ldap:
  url: ldap://localhost:10389
  base: dc=dbs,dc=com
  principal: admin
  credentials: password
  searchFilter: (&(uid=%s))
  
spring:
  ldap:
    base: dc=dbs,dc=comer
    embedded:
      base-dn: dc=dbs,dc=com
      ldif: classpath:schema.ldif
      port: 10389
      credential:
        username: uid=admin
        password: password