spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/priviledge
    username: root
    password: password
  jpa:
    database-platform: org.mariadb.jdbc.Driver
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.hbm2ddl.auto: update
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.integration.envers.enabled: false